import type { PresentationLocale } from "./locales";

export const zhCN = {
  productName: "Night Voyager",
  productPromise: "留学顾问的 AI 协作工作台",
  statusUnavailable: "状态暂不可用",
  localeChinese: "中文",
  localeEnglish: "English",
  syntheticLabel: "本地合成演示",
  documentTitle: "Night Voyager｜留学顾问的 AI 协作工作台",
  documentDescription: "把分散在聊天、资料和研究中的信息，整理成可核对、可沟通、可推进的留学方案。",
  contextPortfolio: "顾问工作台入口",
  contextAdvisorFamily: "顾问到家庭决策流程",
  contextCollaboration: "家庭协作与事实确认流程",
  contextPlanExecution: "治理化计划执行流程",
  journeyOverline: "同一条决策旅程",
  journeyTitle: "从家庭表达走到行动计划",
  journeyDescription: "每一步都由对应角色确认，路线比较与下一步行动保持可追溯。",
  journeyCurrentLabel: "当前阶段",
  journeyCurrentSeparator: "：",
  journeyStageFamilyInput: "家庭表达",
  journeyStageFamilyInputBody: "说清条件、偏好与不能接受的边界。",
  journeyStageAdvisorConfirmation: "顾问确认",
  journeyStageAdvisorConfirmationBody: "顾问核对提案、来源与事实边界。",
  journeyStageRouteReview: "路线比较",
  journeyStageRouteReviewBody: "并列查看结果、依据与路线取舍。",
  journeyStageFamilyDecision: "家庭决定",
  journeyStageFamilyDecisionBody: "家庭明确接受当前路线与取舍。",
  journeyStagePlanExecution: "行动计划",
  journeyStagePlanExecutionBody: "按责任人和行动节点推进，并在需要时停下复核。",
  typedProposalLabel: "结构化事实提案",
  caseRevisionDisclosureLabel: "档案版本",
  factVersionDisclosureLabel: "事实版本",
  caseRevisionTechnicalLabel: "Case revision",
  factVersionTechnicalLabel: "Fact version",
  skillPinDisclosureLabel: "规划能力版本",
  checkpointDisclosureLabel: "行动节点",
  planExecutionEyebrow: "从决定回执到当前行动",
  planExecutionCurrentAction: "当前行动",
  planExecutionConnectPrompt: "选择一个已分配角色，重新验证服务器 authority。",
  planExecutionStart: "开始执行行动计划",
  planExecutionWaitingAdvisor: "家庭可见状态：正在等待已分配顾问验证。",
  planExecutionCompleted: "行动计划已完成。",
  planExecutionReassessment: "当前执行已停止，并进入重新评估交接。",
  planExecutionBlocked: "当前 checkpoint 已阻塞。家庭不能继续提交状态；由已分配顾问决定是否请求重新评估。",
  planExecutionOverdue: "服务器返回当前 checkpoint 已逾期。只有已分配顾问可以请求重新评估。",
  planExecutionReassessmentStop: "重新评估会停止本次执行，且不会创建新计划、决定、时间线或执行。",
  planExecutionRequestReassessment: "请求重新评估并停止执行",
  planExecutionHandoffTitle: "重新评估交接",
  planExecutionHandoffPending: "前序执行记录保持不可变；后续流程等待未来单独授权。",
  planExecutionWhoNext: "下一位行动者：未来获授权的顾问流程。",
  planExecutionBlockedTrigger: "阻塞状态已由顾问接受为重新评估触发条件。",
  planExecutionDeadlineTrigger: "服务器持有的截止日期条件已被接受为重新评估触发条件。",
  planExecutionRecordBlocked: "记录阻塞并停止当前 checkpoint",
  planExecutionBlockedReason: "阻塞原因",
  planExecutionMissingInput: "缺少必需输入",
  planExecutionExternalUnavailable: "外部依赖暂不可用",
  planExecutionDeadlineRisk: "截止日期存在风险",
  planExecutionSessionChanged: "角色或执行 authority 已变化，请重新连接。",
  planExecutionRecoverableError: "流程已安全暂停，本地没有推断业务状态。",
  planExecutionRecover: "重新验证执行 authority",
  planExecutionRoleTitle: "演示角色",
  planExecutionCheckpointTitle: "当前 checkpoint",
  planExecutionCheckpointLabel: "当前节点",
  planExecutionCheckpointState: "节点状态",
  planExecutionAttestationLabel: "checkpoint 状态证明",
  planExecutionProgress: "记录进行中",
  planExecutionSubmitCompletion: "提交完成状态给顾问",
  planExecutionVerificationLabel: "顾问验证",
  planExecutionVerify: "验证并继续",
  planExecutionRequestUpdate: "请求更新",
  planExecutionNoCurrentCheckpoint: "当前没有待处理的 checkpoint。",
  planExecutionDueDate: "截止日期",
  planExecutionOwnerRole: "负责角色",
  planExecutionRiskState: "风险状态",
  planExecutionMilestoneDocuments: "材料准备",
  planExecutionMilestoneApplication: "申请提交",
  planExecutionMilestoneVisa: "签证准备",
  planExecutionMilestoneArrival: "抵达安排",
  planExecutionCheckpointPending: "待开始",
  planExecutionCheckpointInProgress: "进行中",
  planExecutionCheckpointAwaitingAdvisor: "等待顾问",
  planExecutionCheckpointVerified: "已验证",
  planExecutionCheckpointBlocked: "已阻塞",
  planExecutionRiskOnTrack: "按计划",
  planExecutionRiskDueSoon: "临近截止",
  planExecutionRiskOverdue: "已逾期",
  planExecutionNextHandoff: "下一位行动者",
  planExecutionNextAdvisor: "家庭提交后，由已分配顾问验证。",
  planExecutionNextFamily: "顾问验证后，由已批准的下一节点负责角色行动。",
  planExecutionNextFuture: "当前执行停在这里；未来顾问流程需要单独授权。",
  planExecutionNextNone: "执行已完成，无待处理的人工作业。",
  planExecutionApprovedPlanTitle: "已批准的行动计划",
  planExecutionApprovedPlanBody: "节点顺序、负责角色与截止日期来自不可变时间线，本页不能改写。",
  planExecutionActivityTitle: "活动记录",
  planExecutionActivityDisclosure: "查看最新活动细节",
  planExecutionNoActivity: "尚无活动记录。",
  planExecutionActivityShown: "显示",
  planExecutionActivityTotal: "共",
  planExecutionActivityItems: "条",
  planExecutionActivityLatest64: "当前仅显示最近 64 条；更早的保留历史不在此视图中。",
  planExecutionActivityAttestation: "家庭状态更新",
  planExecutionActivityVerification: "顾问验证",
  planExecutionActivityReassessment: "重新评估交接",
  planExecutionActivityReceipt: "操作回执",
  skipToMain: "跳到主要内容",
  localeControlLabel: "展示语言",
  footerBoundary: "本地合成演示，不包含真实学生资料、实时院校覆盖、自动录取建议或生产部署声明。",
  rootKicker: "01 · 顾问工作台",
  rootEyebrow: "AI 协作工作台 · 为留学顾问设计",
  rootTitleLineOne: "把零散咨询，整理成",
  rootTitleLineTwo: "可以推进的留学方案",
  rootTitle: "把零散咨询，整理成可以推进的留学方案",
  rootSummary: "Night Voyager 帮助顾问整理客户信息、核对证据、比较留学路线并推进后续计划。AI 负责研究与草拟，关键判断仍由顾问确认。",
  rootNavigationLabel: "顾问工作台导航",
  rootNavApproach: "顾问工作流",
  rootNavRoutes: "方案研判",
  rootNavEvidence: "核对依据",
  rootHeaderAction: "查看一次完整咨询流程",
  rootOriginLabel: "当前客户档案",
  rootOriginField: "computing",
  rootOriginBudget: "预算 ¥340,000–400,000",
  rootRouteAtlasTitle: "当前方案研判",
  rootRouteAtlasDescription: "当前档案的 intended field 为 computing，预算为 CNY 340,000–400,000。澳大利亚在预算条件下推荐，日本为有条件备选，马来西亚暂不可选。",
  rootRouteSummaryLabel: "路线比较摘要",
  rootRouteRecommended: "在预算条件下推荐",
  rootRouteReserve: "有条件备选",
  rootRouteNotRecommended: "暂不可选",
  rootRouteAustraliaReason: "专业衔接与预算区间更匹配",
  rootRouteJapanReason: "保留语言与时间准备弹性",
  rootRouteMalaysiaReason: "当前专业选择不足以支撑优先级",
  rootJourneyIndex: "02 / 一条工作流，两个证明片段",
  rootJourneyTitleLineOne: "从咨询接入",
  rootJourneyTitleLineTwo: "走到执行跟进",
  rootJourneyLead: "同一 Case 从咨询记录走到客户确认与 TimelinePlan；执行跟进使用独立播种的确定性场景，并在边界处明确标注。",
  rootJourneyStepOneIndex: "01 · 咨询接入",
  rootJourneyStepOneTitle: "记录客户信息",
  rootJourneyStepOneBody: "咨询记录先保持为沟通内容，再由顾问核验需要写入客户档案的信息。",
  rootJourneyStepTwoIndex: "02 · 方案研判",
  rootJourneyStepTwoTitle: "核对理由与证据",
  rootJourneyStepTwoBody: "路线结果、证据充分性和未解决缺口先交给顾问判断，AI 不替代专业确认。",
  rootJourneyStepThreeIndex: "03 · 执行跟进",
  rootJourneyStepThreeTitle: "沿着客户选择推进",
  rootJourneyStepThreeBody: "客户确认形成回执与计划；执行演示是另一个确定性场景，不声称跨场景续接。",
  rootScrollCue: "继续查看顾问工作流",
  rootOutcomeLabel: "当前工作",
  rootOutcome: "让客户信息、路线依据、责任人和下一步保持可核对。",
  rootReasonLabel: "谁负责判断",
  rootReason: "AI 负责整理、研究和草拟；顾问确认专业判断，客户确认个人取舍。",
  rootNextLabel: "开始位置",
  rootNext: "查看一次完整咨询流程，或先看方案如何被核对。",
  rootPrimaryAction: "查看一次完整咨询流程",
  rootSecondaryAction: "了解方案如何被核对",
  rootAuthorityTitle: "顾问工作流与责任边界",
  rootBeatMessageTitle: "咨询记录",
  rootBeatMessageBody: "客户消息保留在共享沟通记录中，不会静默升级为事实。",
  rootBeatFactTitle: "顾问核验",
  rootBeatFactBody: "顾问确认 typed proposal 后，Case revision 才会变化。",
  rootBeatPlanTitle: "客户确认与回执",
  rootBeatPlanBody: "证据门、顾问审核和客户选择共同形成可追溯行动计划。",
  rootScopeTitle: "公开演示边界",
  rootScopeBody: "使用本地合成数据与 deterministic adapters；不调用 live provider，不包含真实学生数据，也不声称生产部署或录取结果。",
  workspaceCategory: "留学顾问的 AI 协作工作台",
  workspaceCaseContext: "客户档案与当前工作",
  workspaceSyntheticBoundary: "本地合成演示 · 仅用于可复核的产品证明",
  workspaceCurrentStage: "当前工作阶段",
  workspaceActiveRole: "当前角色",
  workspaceNextResponsible: "下一位负责者",
  workspaceProofBoundary: "证明片段",
  workspaceTechnicalEvidence: "技术证据（默认收起）",
  workspaceSupportingEvidence: "业务依据",
  workspaceFooter: "本地合成演示；产品行为与权责边界保持在现有确定性流程内。",
  workflowRailLabel: "顾问工作流阶段",
  workflowStageConsultationIntake: "咨询接入",
  workflowStageClientFactReview: "信息核验",
  workflowStageRouteAnalysis: "方案研判",
  workflowStageClientConfirmation: "客户确认",
  workflowStageExecutionFollowup: "执行跟进",
  proofSegmentConnectedSameCase: "同一 Case 的连接证明",
  proofSegmentIndependentExecutionScenario: "独立的确定性执行场景",
  separateExecutionScenario: "执行跟进使用独立播种的 Happy / Blocked 确定性场景，不承接当前 Case 或 session。",
  rootWorkflowTitle: "一条顾问工作流，两个确定性证明片段",
  rootWorkflowBody: "咨询接入、信息核验、方案研判、客户确认和执行跟进保持同一产品模型；连接证明在回执与 TimelinePlan 处结束，执行跟进另行标注。",
  rootResponsibilityTitle: "AI 负责协作，顾问与客户保留判断",
  rootResponsibilityAiTitle: "AI 协作",
  rootResponsibilityAiBody: "整理信息、研究证据、比较路线、草拟方案、跟踪状态。",
  rootResponsibilityHumanTitle: "顾问与客户",
  rootResponsibilityHumanBody: "顾问确认专业判断并推进审核；客户确认个人选择与取舍。",
  rootEngineeringTitle: "工程证据在业务故事之后",
  rootEngineeringBody: "Evidence、确定性 gates、human review、durable task、receipt 和 recovery 支撑可继续处理的工作流。",
  rootEvidenceItemGates: "Evidence 与确定性 eligibility gates",
  rootEvidenceItemHumanReview: "AdvisorReview 与客户确认",
  rootEvidenceItemDurable: "DecisionReceipt、TimelinePlan、durable task 与 recovery",
  rootPreviewTitle: "当前客户档案 · 方案研判",
  rootPreviewBoundary: "静态只读预览 · 使用当前确定性合成 fixture 的闭合投影",
  previewIntendedField: "意向方向",
  previewBudget: "预算边界",
  previewRouteOutcome: "路线结果",
  previewEvidenceSufficiency: "证据充分性",
  previewUnresolvedGap: "未解决缺口",
  previewNextAction: "下一步顾问动作",
  previewReviewRoutes: "核对路线与证据",
  previewEvidenceComplete: "当前证据可供核对",
  previewEvidencePartial: "证据仍有缺口",
  previewGapHighRisk: "高风险替代路线仍需说明",
  previewGapDirectProgramFit: "缺少直接专业匹配证据",
  previewNoKnownGap: "当前投影未记录缺口",
  previewEvidenceMalaysiaContext: "马来西亚背景证据",
  roleAdvisor: "顾问",
  roleStudent: "学生",
  roleParent: "家长",
  countryAustralia: "澳大利亚",
  countryJapan: "日本",
  countryMalaysia: "马来西亚",
  phaseTaskReady: "可以开始规划",
  phaseActiveTask: "正在生成规划",
  phaseReviewRequired: "等待顾问审核",
  phaseRevisionRequested: "等待学生提交修订提案",
  phaseRevisionFactPending: "修订事实等待顾问确认",
  phaseReplanRequired: "需要创建修订规划",
  phaseRevisionTaskActive: "正在生成修订规划",
  phaseRevisionReviewRequired: "修订计划等待顾问批准",
  phaseRevisionBlocked: "修订计划已被规则阻止",
  phaseFamilyReview: "等待家庭确认",
  phasePlanReady: "行动计划已就绪",
  phaseTerminalTaskFailure: "规划任务已暂停",
  taskPreparing: "正在准备",
  taskNeedsAdvisorReview: "需要顾问审核",
  taskReady: "已完成",
  taskNeedsEvidence: "需要补充证据",
  taskTimedOut: "已超时",
  taskFailed: "未完成",
  taskCancelled: "已取消",
  taskOutdated: "已有更新版本",
  routeRecommendedWithCondition: "在预算条件下推荐",
  routeConditional: "有条件备选",
  routeBlocked: "暂不可选",
  reasonCompleteCostAndFx: "成本与汇率证据均在已批准边界内",
  reasonSyntheticHighRisk: "较高风险的合成备选方案",
  reasonProgramFitAbsent: "缺少直接的项目匹配证据",
  tradeOffBudgetElasticity: "预算弹性",
  candidatePending: "等待顾问确认",
  candidateStale: "所依据的 Case revision 已更新",
  candidateExpired: "候选事实已过期",
  candidateConfirmed: "已确认进入事实记录",
  candidateRejected: "未被采纳",
  errorStale: "页面状态已更新，请重新载入",
  errorExpiredOrTerminal: "该候选事实已结束，不能继续操作",
  errorActiveTaskBlocked: "当前规划任务结束前不能修改事实",
  errorUnsafeOrUnsupported: "输入未通过安全或合同校验",
  errorWrongRoleOrNotFound: "当前角色无法访问该记录",
  errorSessionRecoveryRequired: "会话需要安全恢复",
  errorTransportUnavailable: "连接暂不可用，请稍后重试",
  pinNotCreated: "尚未创建 Skill pin",
  pinMatched: "运行时 Skill pin 已匹配",
  pinLegacyUnpinned: "旧任务没有 Skill pin",
  riskOptional: "可选风险",
  riskStale: "证据可能已过时",
  riskUnverified: "证据尚未验证",
  sourceDirect: "家庭直接确认",
  sourceFamilyConsultation: "家庭协商确认",
  advisorStageTitle: "当前决策阶段",
  advisorLedgerOverline: "顾问决策台 · 全局流程",
  activeRoleLabel: "当前角色",
  advisorRoleAuthority: "顾问可以执行本阶段明确授权的审核或规划动作。",
  studentRoleAuthority: "学生只能提交可见的事实变更提案，不能确认事实。",
  parentRoleAuthority: "家长只能确认服务器提供的当前决定简报。",
  advisorStageAuthority: "阶段与可执行动作来自服务器 authority projection。",
  advisorCreateTask: "创建规划任务",
  advisorApproveAustralia: "批准澳大利亚进入家庭审核",
  advisorContinueFamily: "以家庭角色继续",
  advisorTaskInProgress: "任务正在进行",
  approveCurrentPlanAction: "批准当前计划",
  requestRevisionAction: "请求修订",
  confirmRevisionFactAction: "确认意向国家变更",
  createRevisedTaskAction: "创建修订规划任务",
  approveRevisedPlanAction: "批准修订计划",
  continueFamilyDecisionAction: "继续家庭决定",
  revisionBlockedTitle: "此修订已被确定性规则阻止",
  revisionBlockedBody: "当前计划不可批准；请保留比较记录并返回安全导航。",
  terminalFailureTitle: "规划任务未完成",
  noBusinessAction: "此阶段没有可执行的业务变更。",
  safeNavigationExit: "返回产品概览",
  advisorActionExplanation: "此阶段只有一个服务器授权的主要动作。",
  routeComparisonLabel: "路线证据比较",
  routeColumn: "路线",
  outcomeColumn: "结果",
  reasonColumn: "理由",
  eligibilityColumn: "审核资格",
  eligibleForReview: "符合审核条件",
  notEligibleForReview: "不符合审核条件",
  compareRoutes: "比较国家路线",
  requiredClaims: "所需证据主张",
  knownGaps: "已知缺口",
  noRequiredClaims: "没有投影的必需主张",
  noKnownGaps: "没有投影的已知缺口",
  noRoutes: "路线比较尚未生成。",
  currentFactsOverline: "服务器持有的当前 Case authority",
  currentFactsTitle: "当前已确认家庭事实",
  currentFactsUnavailable: "服务器事实投影刷新前，当前事实暂不可用。",
  currentFactsEmpty: "此 Case revision 尚无已确认事实。",
  factLabel: "事实",
  currentValueLabel: "当前值",
  factAuthorityLabel: "事实 authority",
  caseAuthorityLabel: "Case authority",
  factVersionLabel: "事实版本",
  caseRevisionLabel: "档案版本",
  currentCaseRevisionLabel: "当前 Case revision",
  revisionComparisonOverline: "服务器生成的版本差异",
  revisionComparisonTitle: "规划修订比较",
  changedFactTitle: "已确认事实变更",
  preferredCountriesChanged: "学生意向国家已由上一版范围更新为当前范围。",
  familyBudgetChanged: "家庭预算已由上一版边界更新为当前边界。",
  previousValueLabel: "上一版事实",
  revisedValueLabel: "当前事实",
  previousPlanLabel: "保留的上一版计划",
  currentRevisedPlanLabel: "当前修订计划",
  historyOnlyLabel: "历史记录，仅用于比较",
  currentPlanLabel: "当前权威计划",
  comparisonCountryColumn: "国家",
  comparisonPreviousColumn: "上一版结果",
  comparisonCurrentColumn: "当前结果",
  comparisonChangeColumn: "变化",
  compareRevisionCountries: "选择要比较的国家",
  removedFromRevisedPlan: "已从修订计划中移除",
  notPresentInPreviousPlan: "上一版计划中不存在",
  deltaAdded: "已加入修订计划",
  deltaRemoved: "已从修订计划中移除",
  deltaChanged: "结果已变化",
  deltaUnchanged: "结果未变化",
  revisionFactEditorLegend: "修改意向国家",
  revisionFactEditorBody: "仅提交此合成演示批准的国家范围；顾问仍负责确认事实。",
  revisionCurrentCountries: "当前服务器事实",
  revisionTargetCountries: "提议的新范围",
  submitRevisionProposalAction: "提交变更提案",
  revisionEditorUnavailable: "当前服务器事实不符合此合成修订的安全基线。",
  familyRevisionVersionInitial: "初始规划版本",
  familyRevisionVersionRevised: "当前修订规划",
  familyAuthorizationInitial: "顾问已授权初始版本",
  familyAuthorizationRenewed: "顾问已为当前修订重新授权",
  evidenceOverline: "证据披露",
  evidenceTitle: "已接受的合成证据与限制",
  evidencePublisherLabel: "发布方",
  evidenceLimitationLabel: "证据限制",
  evidenceSnapshotLabel: "快照日期",
  taskStatusLabel: "状态",
  taskAttemptLabel: "尝试次数",
  taskTrailSummary: "任务记录",
  taskPublicResult: "公开结果",
  taskDurablePending: "处理期间保留 durable task 记录。",
  familyBriefOverline: "适合家庭阅读的持久化投影",
  familyBriefTitle: "家庭决定简报",
  familyBriefOutcome: "经顾问审核的 Brief 选择澳大利亚作为符合条件的路线。",
  pinnedCostLabel: "澳大利亚锁定成本",
  hardCeilingLabel: "预算硬上限",
  requiredTradeOffLabel: "必须接受的取舍",
  familyConfirmLabel: "我确认这段由服务器生成的人民币区间，并接受预算弹性取舍。",
  familyConfirmAction: "确认澳大利亚路线",
  familyConfirmationRequired: "需要家庭明确确认后才能继续。",
  receiptOverline: "持久化决定记录",
  receiptTitle: "家庭决定回执",
  receiptSummary: "家庭从已审核并持久化的 Brief 中确认了澳大利亚路线。",
  acceptedBudgetLabel: "已接受预算",
  acceptedTradeOffLabel: "已接受取舍",
  decisionSourceLabel: "决定来源",
  timelineTitle: "行动时间线",
  intakeLabel: "入学批次",
  milestoneDocuments: "文件准备",
  milestoneApplication: "提交申请",
  milestoneVisa: "签证准备",
  milestoneArrival: "抵达准备",
  recoveryTitle: "需要恢复",
  recoveryInvalidTransition: "页面进入了不支持的状态，流程已安全停止。",
  recoverySessionExpired: "会话已过期；需要重新建立顾问会话。",
  recoverySessionRequired: "检测到残留会话；需要先执行安全恢复。",
  recoveryStaleConflict: "服务器记录已更新；重新载入后才能继续。",
  recoveryTransportFailure: "连接暂不可用；当前流程没有执行新的变更。",
  recoveryBoundary: "没有执行 mutation，也没有假定新的角色 authority。",
  recoveryReconnect: "重新连接顾问流程",
  journeyConflictTitle: "另一个演示流程正在进行",
  journeyAdvisorFamily: "顾问到家庭流程",
  journeyCollaboration: "家庭协作流程",
  journeyConflictBody: "同一标签页中的当前流程仍具有 authority。开始另一流程前，必须通过服务器结束当前流程。",
  journeyReturn: "返回当前流程",
  journeyEnd: "结束当前流程并继续",
  demoStartOverline: "本地合成试点",
  demoStartTitle: "顾问到家庭的决策流程",
  demoStartBody: "依次经过真实的会话、任务、顾问审核、家庭决定、回执与时间线边界。",
  demoStartAction: "开始顾问流程",
  demoSwitchingTitle: "正在切换到家庭角色",
  demoSwitchingBody: "顾问会话已撤销，正在建立家长会话。",
  demoSwitchingStudentTitle: "正在切换到学生角色",
  demoSwitchingStudentBody: "顾问会话已撤销，正在建立学生会话。",
  demoSwitchingAdvisorTitle: "正在切换到顾问角色",
  demoSwitchingAdvisorBody: "参与者会话已撤销，正在恢复顾问 authority。",
  continueAsStudentAction: "以学生身份继续",
  continueAsAdvisorAction: "以顾问身份继续",
  continueAsParentAction: "以家长身份继续",
  revisionProposalTitle: "提交学生意向国家变更",
  revisionProposalBody: "学生提交可见提案，不直接确认 Case 事实。",
  revisionFactPendingTitle: "审核学生变更提案",
  revisionFactPendingBody: "顾问确认后，服务器才会生成新的 Case revision。",
  loadingStatus: "正在载入服务器 authority…",
  busyStatus: "正在提交变更；保留上一份服务器投影。",
  demoRecordingDecision: "正在记录家庭决定",
  reasonBudgetAboveHardCeiling: "高于家庭预算硬上限",
  reasonBudgetBoundaryExceeded: "超出家庭预算硬上限或弹性边界",
  claimAustraliaProgramFit: "澳大利亚项目匹配",
  claimJapanProgramFit: "日本项目匹配",
  claimMalaysiaProgramFit: "马来西亚项目匹配",
  claimAustraliaTuition: "澳大利亚学费",
  claimAustraliaLivingCost: "澳大利亚生活成本",
  claimAustraliaFx: "澳大利亚汇率",
  claimAustraliaRanking: "澳大利亚排名",
  claimJapanTuition: "日本学费",
  claimJapanLivingCost: "日本生活成本",
  claimJapanFx: "日本汇率",
  claimJapanRanking: "日本排名",
  claimMalaysiaTuition: "马来西亚学费",
  claimMalaysiaLivingCost: "马来西亚生活成本",
  claimMalaysiaFx: "马来西亚汇率",
  claimMalaysiaRanking: "马来西亚排名",
  gapJapanProgramFit: "缺少日本项目匹配证据",
  gapMalaysiaProgramFit: "缺少马来西亚项目匹配证据",
  gapApplicantEligibility: "申请人资格仍待确认",
  gapIntakeAvailability: "入学批次可用性仍待确认",
  factFamilyBudget: "家庭总预算",
  factStudentField: "学生意向专业",
  factPreferredCountries: "意向国家",
  factStudentIntake: "意向入学批次",
  factRiskTolerance: "家庭风险偏好",
  factJapanRiskAccepted: "家庭接受日本路线风险",
  factValueRiskLow: "低",
  factValueRiskMedium: "中等",
  factValueRiskHigh: "高",
  factValueAccepted: "已接受",
  factValueNotAccepted: "未接受",
  factValueBudgetRefused: "家庭选择不提供预算",
  publicCancelled: "任务已由用户取消",
  publicLeaseExpired: "任务租约已过期",
  publicEvidenceGap: "任务需要更多证据",
  publicDeadlineExceeded: "任务超过时间边界",
  publicTransportInterrupted: "任务连接中断",
  publicTransientUnavailable: "规划适配器暂不可用",
  threadOverline: "共享沟通记录",
  threadTitle: "共享 Case 沟通记录",
  threadLoading: "正在加载服务器沟通记录…",
  threadEmpty: "尚无参与者消息。",
  messageSequenceLabel: "消息",
  messageOriginalLabel: "消息原文",
  candidateOverline: "结构化参与者提案",
  candidateTitle: "预算事实提案",
  candidateBudgetLabel: "规划预算",
  candidateSourceLabel: "来源",
  candidateParentMessage: "家长消息",
  candidatePinnedRevision: "锁定的 Case revision",
  candidateAdvisorReason: "顾问理由",
  advisorReasonOriginalLabel: "顾问确认原文",
  confirmedFactOverline: "Case authority 来源",
  confirmedFactTitle: "已确认家庭事实",
  confirmedFactProjection: "现已进入当前 Case projection。",
  confirmedByLabel: "确认人",
  assignedAdvisor: "指定顾问",
  recordedReasonLabel: "记录理由",
  collaborationHeroOverline: "本地合成试点 · 完整协作入口",
  collaborationTitle: "家庭协作与事实确认",
  collaborationLede: "家长消息只有经过显式操作才成为 typed proposal，并且只有指定顾问确认后才成为 Case 事实。",
  currentRoleLabel: "当前角色",
  collaborationPathLabel: "协作 authority 路径",
  pathSharedMessage: "共享消息",
  pathTypedProposal: "Typed proposal",
  pathAdvisorReview: "顾问审核",
  pathConfirmedFact: "已确认事实",
  pathCaseRevision: "Case revision",
  pathReplanRequired: "需要重新规划",
  collaborationStartParent: "开始家长流程",
  parentProposeTitle: "提交一项 typed 家庭事实",
  parentMessageTitle: "添加家庭已确认预算",
  parentProposalPending: "提案会保持待处理，直到指定顾问审核。",
  parentMessageBoundary: "这条消息仍是沟通内容，不会改变 Case。",
  parentProposeAction: "提交预算供顾问审核",
  parentMessageAction: "添加已确认预算消息",
  recordingMessageTitle: "正在记录家长消息",
  recordingMessageAction: "正在记录消息…",
  moveAdvisorTitle: "进入顾问审核",
  moveAdvisorBody: "建立顾问会话前，必须先撤销家长会话。",
  moveAdvisorAction: "以指定顾问身份继续",
  switchingAuthorityTitle: "正在切换 authority",
  switchingAuthorityBody: "正在撤销家长会话并载入顾问 projection。",
  switchingRoleAction: "正在切换角色…",
  advisorConfirmationTitle: "顾问确认",
  advisorConfirmationBody: "确认前，候选事实 revision 必须与当前 Case revision 一致。",
  advisorConfirmBudget: "确认家庭预算",
  advisorReloadBoundary: "确认前请重新载入当前 Case 与候选事实 authority。",
  publishingAuthorityTitle: "正在发布已确认 authority",
  publishingAuthorityAction: "正在确认事实与 Case revision…",
  replanTitle: "需要重新规划",
  replanBody: "Case revision 已变化。此流程不会创建任务；目标页面会先重载当前 authority，再由顾问显式启动规划。",
  replanAction: "继续进入受治理规划",
  handoffTitle: "正在验证规划 authority",
  handoffBody: "导航前正在重载当前候选事实、已确认事实、Case revision 与顾问 ledger。",
  handoffAction: "正在验证 authority…",
  collaborationRecoveryTitle: "协作流程已安全暂停",
  collaborationRecoveryBoundary: "本地没有推断消息、提案、角色或 Case authority。",
  collaborationRecoveryAction: "重新载入协作 authority",
  skillInspectorTitle: "规划 Skill 检查器",
  skillInspectorBody: "这个只读 projection 来自服务器持有的规划执行记录。",
  skillOperationLabel: "Operation",
  skillActiveLabel: "Active Skill",
  skillActivationLabel: "Activation",
  skillSequenceLabel: "Sequence",
  skillEvaluationLabel: "Evaluation",
  skillTaskRequestLabel: "Task request",
  skillVersionContentLabel: "Version content",
  skillRuntimeBindingLabel: "Runtime binding",
  skillAdapterLabel: "Actual adapter",
  skillNoOperation: "尚未创建规划任务",
  skillNoTaskDigest: "尚无 task digest",
  skillNoAdapter: "未记录 leaf adapter",
} as const;

export type PresentationCopyKey = keyof typeof zhCN;

export const en = {
  productName: "Night Voyager",
  productPromise: "AI collaboration workspace for study-abroad advisors",
  statusUnavailable: "Status unavailable",
  localeChinese: "中文",
  localeEnglish: "English",
  syntheticLabel: "Local synthetic demo",
  documentTitle: "Night Voyager | AI Collaboration Workspace for Study-Abroad Advisors",
  documentDescription: "Turn fragmented conversations, evidence, and route research into a reviewable client plan.",
  contextPortfolio: "Advisor workspace entry",
  contextAdvisorFamily: "Advisor-to-family decision flow",
  contextCollaboration: "Family collaboration and fact confirmation",
  contextPlanExecution: "Governed plan execution flow",
  journeyOverline: "One decision journey",
  journeyTitle: "From family input to an action plan",
  journeyDescription: "Each stage is confirmed by the responsible role, keeping route trade-offs and next actions traceable.",
  journeyCurrentLabel: "Current stage",
  journeyCurrentSeparator: ": ",
  journeyStageFamilyInput: "Family input",
  journeyStageFamilyInputBody: "Make the conditions, preferences, and boundaries explicit.",
  journeyStageAdvisorConfirmation: "Advisor confirmation",
  journeyStageAdvisorConfirmationBody: "The advisor checks the proposal, sources, and fact boundary.",
  journeyStageRouteReview: "Route review",
  journeyStageRouteReviewBody: "Compare outcomes, evidence, and trade-offs side by side.",
  journeyStageFamilyDecision: "Family decision",
  journeyStageFamilyDecisionBody: "The family explicitly accepts the current route and trade-offs.",
  journeyStagePlanExecution: "Plan execution",
  journeyStagePlanExecutionBody: "Move through accountable checkpoints and pause for review when needed.",
  typedProposalLabel: "typed proposal",
  caseRevisionDisclosureLabel: "Case revision",
  factVersionDisclosureLabel: "Fact version",
  caseRevisionTechnicalLabel: "Case revision",
  factVersionTechnicalLabel: "Fact version",
  skillPinDisclosureLabel: "Skill pin",
  checkpointDisclosureLabel: "checkpoint",
  planExecutionEyebrow: "From decision receipt to current action",
  planExecutionCurrentAction: "Current action",
  planExecutionConnectPrompt: "Choose an assigned role and revalidate server authority.",
  planExecutionStart: "Start the action plan",
  planExecutionWaitingAdvisor: "Family view: waiting for the assigned advisor to verify.",
  planExecutionCompleted: "The action plan is complete.",
  planExecutionReassessment: "This execution has stopped and entered reassessment handoff.",
  planExecutionBlocked: "The current checkpoint is blocked. Family updates stop here; the assigned advisor decides whether to request reassessment.",
  planExecutionOverdue: "The server reports that the current checkpoint is overdue. Only the assigned advisor may request reassessment.",
  planExecutionReassessmentStop: "Reassessment stops this execution and does not create a new plan, decision, timeline, or execution.",
  planExecutionRequestReassessment: "Request reassessment and stop execution",
  planExecutionHandoffTitle: "Reassessment handoff",
  planExecutionHandoffPending: "The predecessor execution stays immutable; any next workflow awaits separate future authorization.",
  planExecutionWhoNext: "Who acts next: a future separately authorized advisor workflow.",
  planExecutionBlockedTrigger: "The blocker was accepted by the advisor as the reassessment trigger.",
  planExecutionDeadlineTrigger: "The server-owned deadline condition was accepted as the reassessment trigger.",
  planExecutionRecordBlocked: "Record blocker and stop the current checkpoint",
  planExecutionBlockedReason: "Blocker reason",
  planExecutionMissingInput: "Required input is missing",
  planExecutionExternalUnavailable: "External dependency is unavailable",
  planExecutionDeadlineRisk: "Deadline is at risk",
  planExecutionSessionChanged: "Role or execution authority changed. Reconnect safely.",
  planExecutionRecoverableError: "The flow paused safely; no business state was inferred locally.",
  planExecutionRecover: "Revalidate execution authority",
  planExecutionRoleTitle: "Demo role",
  planExecutionCheckpointTitle: "Current checkpoint",
  planExecutionCheckpointLabel: "Current milestone",
  planExecutionCheckpointState: "Milestone state",
  planExecutionAttestationLabel: "Checkpoint attestation",
  planExecutionProgress: "Record progress",
  planExecutionSubmitCompletion: "Submit completion to advisor",
  planExecutionVerificationLabel: "Advisor verification",
  planExecutionVerify: "Verify and continue",
  planExecutionRequestUpdate: "Request update",
  planExecutionNoCurrentCheckpoint: "There is no current checkpoint.",
  planExecutionDueDate: "Due date",
  planExecutionOwnerRole: "Owner role",
  planExecutionRiskState: "Risk state",
  planExecutionMilestoneDocuments: "Documents",
  planExecutionMilestoneApplication: "Application",
  planExecutionMilestoneVisa: "Visa",
  planExecutionMilestoneArrival: "Arrival",
  planExecutionCheckpointPending: "Not started",
  planExecutionCheckpointInProgress: "In progress",
  planExecutionCheckpointAwaitingAdvisor: "Awaiting advisor",
  planExecutionCheckpointVerified: "Verified",
  planExecutionCheckpointBlocked: "Blocked",
  planExecutionRiskOnTrack: "On track",
  planExecutionRiskDueSoon: "Due soon",
  planExecutionRiskOverdue: "Overdue",
  planExecutionNextHandoff: "Who acts next",
  planExecutionNextAdvisor: "After the family submits, the assigned advisor verifies.",
  planExecutionNextFamily: "After advisor verification, the approved next checkpoint owner acts.",
  planExecutionNextFuture: "Execution stops here; a future advisor workflow requires separate authorization.",
  planExecutionNextNone: "Execution is complete with no pending human action.",
  planExecutionApprovedPlanTitle: "Approved action plan",
  planExecutionApprovedPlanBody: "Milestone order, owner roles, and due dates come from the immutable timeline and cannot be rewritten here.",
  planExecutionActivityTitle: "Activity",
  planExecutionActivityDisclosure: "Review latest activity details",
  planExecutionNoActivity: "No activity yet.",
  planExecutionActivityShown: "Showing",
  planExecutionActivityTotal: "Total",
  planExecutionActivityItems: "items",
  planExecutionActivityLatest64: "This view shows the latest 64 items only; older retained history is not displayed here.",
  planExecutionActivityAttestation: "Family status update",
  planExecutionActivityVerification: "Advisor verification",
  planExecutionActivityReassessment: "Reassessment handoff",
  planExecutionActivityReceipt: "Operation receipt",
  skipToMain: "Skip to main content",
  localeControlLabel: "Presentation language",
  footerBoundary: "Local synthetic demo: no real student records, live institutional coverage, automated admissions advice, or production deployment claim.",
  rootKicker: "01 · Advisor workspace",
  rootEyebrow: "AI collaboration workspace for study-abroad advisors",
  rootTitleLineOne: "Turn scattered consultations into",
  rootTitleLineTwo: "a client plan you can move forward",
  rootTitle: "Turn scattered consultations into a client plan you can move forward",
  rootSummary: "Night Voyager helps advisors organize client facts, review evidence, compare study routes, and carry the decision into execution. AI researches and drafts; the advisor keeps professional judgment.",
  rootNavigationLabel: "Advisor workspace navigation",
  rootNavApproach: "Advisor workflow",
  rootNavRoutes: "Route analysis",
  rootNavEvidence: "Verification evidence",
  rootHeaderAction: "Walk through one client case",
  rootOriginLabel: "Current client case",
  rootOriginField: "computing",
  rootOriginBudget: "Budget CNY 340,000–400,000",
  rootRouteAtlasTitle: "Current route analysis",
  rootRouteAtlasDescription: "The current case has intended field computing and a CNY 340,000–400,000 budget. Australia is recommended with a budget condition, Japan is a conditional alternative, and Malaysia is blocked.",
  rootRouteSummaryLabel: "Route comparison summary",
  rootRouteRecommended: "Recommended with budget condition",
  rootRouteReserve: "Conditional alternative",
  rootRouteNotRecommended: "Blocked",
  rootRouteAustraliaReason: "The program pathway and budget range are the strongest match",
  rootRouteJapanReason: "Preserves flexibility for language and timeline preparation",
  rootRouteMalaysiaReason: "Current program options do not support a higher priority",
  rootJourneyIndex: "02 / One workflow, two proof segments",
  rootJourneyTitleLineOne: "From consultation intake",
  rootJourneyTitleLineTwo: "to execution follow-up",
  rootJourneyLead: "The same Case moves from consultation record to client confirmation and TimelinePlan. Execution follow-up uses an independently seeded deterministic scenario and is labelled at that boundary.",
  rootJourneyStepOneIndex: "01 · Consultation intake",
  rootJourneyStepOneTitle: "Record client information",
  rootJourneyStepOneBody: "A consultation record remains communication until the advisor verifies what belongs in the client case.",
  rootJourneyStepTwoIndex: "02 · Route analysis",
  rootJourneyStepTwoTitle: "Verify reasons and evidence",
  rootJourneyStepTwoBody: "Route outcomes, evidence sufficiency, and unresolved gaps come to the advisor before professional judgment is confirmed.",
  rootJourneyStepThreeIndex: "03 · Execution follow-up",
  rootJourneyStepThreeTitle: "Carry the client choice forward",
  rootJourneyStepThreeBody: "Client confirmation creates a receipt and plan; the execution demo is a separate deterministic scenario with no cross-scenario handoff.",
  rootScrollCue: "Continue through the advisor workflow",
  rootOutcomeLabel: "Current work",
  rootOutcome: "Keep client facts, route evidence, responsibility, and next action reviewable.",
  rootReasonLabel: "Who decides",
  rootReason: "AI organizes, researches, and drafts; the advisor confirms professional judgment and the client confirms personal trade-offs.",
  rootNextLabel: "Start here",
  rootNext: "Walk through one client case or see how a proposal is verified.",
  rootPrimaryAction: "Walk through one client case",
  rootSecondaryAction: "See how the proposal is verified",
  rootAuthorityTitle: "Advisor workflow and responsibility boundaries",
  rootBeatMessageTitle: "Consultation record",
  rootBeatMessageBody: "Client messages remain in the shared communication record and never silently become facts.",
  rootBeatFactTitle: "Advisor verification",
  rootBeatFactBody: "The Case revision changes only after an advisor confirms a typed proposal.",
  rootBeatPlanTitle: "Client confirmation and receipt",
  rootBeatPlanBody: "Evidence gates, advisor review, and client choice produce a traceable action plan.",
  rootScopeTitle: "Public demo boundary",
  rootScopeBody: "Uses local synthetic data and deterministic adapters; no live provider, real student data, production deployment claim, or admissions outcome.",
  workspaceCategory: "AI collaboration workspace for study-abroad advisors",
  workspaceCaseContext: "Client case and current work",
  workspaceSyntheticBoundary: "Local synthetic demo · bounded product proof only",
  workspaceCurrentStage: "Current workflow stage",
  workspaceActiveRole: "Active role",
  workspaceNextResponsible: "Next responsible participant",
  workspaceProofBoundary: "Proof segment",
  workspaceTechnicalEvidence: "Technical evidence (closed by default)",
  workspaceSupportingEvidence: "Business evidence",
  workspaceFooter: "Local synthetic demo; product behavior and authority boundaries remain in the existing deterministic flow.",
  workflowRailLabel: "Advisor workflow stages",
  workflowStageConsultationIntake: "Consultation intake",
  workflowStageClientFactReview: "Client fact review",
  workflowStageRouteAnalysis: "Route analysis",
  workflowStageClientConfirmation: "Client confirmation",
  workflowStageExecutionFollowup: "Execution follow-up",
  proofSegmentConnectedSameCase: "Connected same-Case proof",
  proofSegmentIndependentExecutionScenario: "Independent deterministic execution scenario",
  separateExecutionScenario: "Execution follow-up uses an independently seeded Happy / Blocked deterministic scenario; it does not carry this Case or session forward.",
  rootWorkflowTitle: "One advisor workflow, two deterministic proof segments",
  rootWorkflowBody: "Consultation intake, client fact review, route analysis, client confirmation, and execution follow-up share one product model. The connected proof ends at the receipt and TimelinePlan; execution follow-up is labelled separately.",
  rootResponsibilityTitle: "AI collaborates; the advisor and client keep judgment",
  rootResponsibilityAiTitle: "AI collaboration",
  rootResponsibilityAiBody: "Organize information, research evidence, compare routes, draft proposals, and track state.",
  rootResponsibilityHumanTitle: "Advisor and client",
  rootResponsibilityHumanBody: "The advisor confirms professional judgment and review; the client confirms personal choice and trade-offs.",
  rootEngineeringTitle: "Engineering evidence follows the business story",
  rootEngineeringBody: "Evidence, deterministic gates, human review, durable task state, receipt, and recovery support a workflow that can continue safely.",
  rootEvidenceItemGates: "Evidence and deterministic eligibility gates",
  rootEvidenceItemHumanReview: "AdvisorReview and client confirmation",
  rootEvidenceItemDurable: "DecisionReceipt, TimelinePlan, durable task state, and recovery",
  rootPreviewTitle: "Current client case · route analysis",
  rootPreviewBoundary: "Static read-only preview · closed projection of the current deterministic synthetic fixture",
  previewIntendedField: "Intended field",
  previewBudget: "Budget boundary",
  previewRouteOutcome: "Route outcome",
  previewEvidenceSufficiency: "Evidence sufficiency",
  previewUnresolvedGap: "Unresolved gap",
  previewNextAction: "Next advisor action",
  previewReviewRoutes: "Review routes and evidence",
  previewEvidenceComplete: "Evidence is available for review",
  previewEvidencePartial: "Evidence still has a gap",
  previewGapHighRisk: "High-risk alternative still needs explanation",
  previewGapDirectProgramFit: "Direct program-fit evidence is absent",
  previewNoKnownGap: "No gap is recorded in this projection",
  previewEvidenceMalaysiaContext: "Malaysia context evidence",
  roleAdvisor: "Advisor",
  roleStudent: "Student",
  roleParent: "Parent",
  countryAustralia: "Australia",
  countryJapan: "Japan",
  countryMalaysia: "Malaysia",
  phaseTaskReady: "Ready to plan",
  phaseActiveTask: "Planning in progress",
  phaseReviewRequired: "Advisor review required",
  phaseRevisionRequested: "Waiting for the student revision proposal",
  phaseRevisionFactPending: "Revision fact needs advisor confirmation",
  phaseReplanRequired: "Revised planning task required",
  phaseRevisionTaskActive: "Revised planning in progress",
  phaseRevisionReviewRequired: "Revised plan needs advisor approval",
  phaseRevisionBlocked: "Revision blocked by deterministic policy",
  phaseFamilyReview: "Family confirmation required",
  phasePlanReady: "Action plan ready",
  phaseTerminalTaskFailure: "Planning task paused",
  taskPreparing: "Preparing",
  taskNeedsAdvisorReview: "Needs advisor review",
  taskReady: "Ready",
  taskNeedsEvidence: "Needs more evidence",
  taskTimedOut: "Timed out",
  taskFailed: "Failed",
  taskCancelled: "Cancelled",
  taskOutdated: "Superseded",
  routeRecommendedWithCondition: "Recommended with budget condition",
  routeConditional: "Conditional alternative",
  routeBlocked: "Blocked",
  reasonCompleteCostAndFx: "Cost and FX evidence are within the approved boundary",
  reasonSyntheticHighRisk: "Higher-risk synthetic alternative",
  reasonProgramFitAbsent: "Program-fit evidence is missing",
  tradeOffBudgetElasticity: "Budget flexibility",
  candidatePending: "Awaiting advisor confirmation",
  candidateStale: "Based on an older Case revision",
  candidateExpired: "Candidate fact expired",
  candidateConfirmed: "Confirmed in the fact record",
  candidateRejected: "Not accepted",
  errorStale: "The page state changed; reload before continuing",
  errorExpiredOrTerminal: "This candidate fact has ended and cannot continue",
  errorActiveTaskBlocked: "Facts cannot change while a planning task is active",
  errorUnsafeOrUnsupported: "The input did not pass safety or contract validation",
  errorWrongRoleOrNotFound: "This role cannot access the record",
  errorSessionRecoveryRequired: "The session needs a safe recovery",
  errorTransportUnavailable: "The connection is unavailable; try again",
  pinNotCreated: "Skill pin not created",
  pinMatched: "Runtime Skill pin matched",
  pinLegacyUnpinned: "Legacy task has no Skill pin",
  riskOptional: "Optional risk",
  riskStale: "Evidence may be stale",
  riskUnverified: "Evidence is unverified",
  sourceDirect: "Direct family confirmation",
  sourceFamilyConsultation: "Family consultation",
  advisorStageTitle: "Current decision stage",
  advisorLedgerOverline: "Advisor decision desk · global journey",
  activeRoleLabel: "Active role",
  advisorRoleAuthority: "The advisor may perform only the review or planning action authorized for this phase.",
  studentRoleAuthority: "The student may submit a visible fact-change proposal and cannot confirm a fact.",
  parentRoleAuthority: "The parent may confirm only the current server-provided Decision Brief.",
  advisorStageAuthority: "The stage and available action come from the server authority projection.",
  advisorCreateTask: "Create planning task",
  advisorApproveAustralia: "Approve Australia for family review",
  advisorContinueFamily: "Continue as family",
  advisorTaskInProgress: "Task in progress",
  approveCurrentPlanAction: "Approve current plan",
  requestRevisionAction: "Request revision",
  confirmRevisionFactAction: "Confirm preferred-country change",
  createRevisedTaskAction: "Create revised planning task",
  approveRevisedPlanAction: "Approve revised plan",
  continueFamilyDecisionAction: "Continue family decision",
  revisionBlockedTitle: "This revision was blocked by deterministic policy",
  revisionBlockedBody: "The current plan cannot be approved; retain the comparison and use the safe navigation exit.",
  terminalFailureTitle: "Planning task did not complete",
  noBusinessAction: "No business mutation is available in this phase.",
  safeNavigationExit: "Return to product overview",
  advisorActionExplanation: "One server-authorized primary action is available in this stage.",
  routeComparisonLabel: "Route evidence comparison",
  routeColumn: "Route",
  outcomeColumn: "Outcome",
  reasonColumn: "Reason",
  eligibilityColumn: "Eligibility",
  eligibleForReview: "Eligible for review",
  notEligibleForReview: "Not eligible for review",
  compareRoutes: "Compare country routes",
  requiredClaims: "Required claims",
  knownGaps: "Known gaps",
  noRequiredClaims: "No projected required claims",
  noKnownGaps: "No projected known gaps",
  noRoutes: "Route comparison has not been generated.",
  currentFactsOverline: "Current server-owned Case authority",
  currentFactsTitle: "Current confirmed family facts",
  currentFactsUnavailable: "Current facts are unavailable until the server projection refreshes.",
  currentFactsEmpty: "No confirmed facts are projected for this Case revision.",
  factLabel: "Fact",
  currentValueLabel: "Current value",
  factAuthorityLabel: "Fact authority",
  caseAuthorityLabel: "Case authority",
  factVersionLabel: "Fact version",
  caseRevisionLabel: "Case revision",
  currentCaseRevisionLabel: "Current Case revision",
  revisionComparisonOverline: "Server-generated version delta",
  revisionComparisonTitle: "Planning revision comparison",
  changedFactTitle: "Confirmed fact change",
  preferredCountriesChanged: "The student's preferred-country scope changed from the previous range to the current range.",
  familyBudgetChanged: "The family budget changed from the previous boundary to the current boundary.",
  previousValueLabel: "Previous fact",
  revisedValueLabel: "Current fact",
  previousPlanLabel: "Previous plan retained for history",
  currentRevisedPlanLabel: "Current revised plan",
  historyOnlyLabel: "History, for comparison only",
  currentPlanLabel: "Current authoritative plan",
  comparisonCountryColumn: "Country",
  comparisonPreviousColumn: "Previous result",
  comparisonCurrentColumn: "Current result",
  comparisonChangeColumn: "Change",
  compareRevisionCountries: "Choose a country to compare",
  removedFromRevisedPlan: "Removed from the revised plan",
  notPresentInPreviousPlan: "Not present in the previous plan",
  deltaAdded: "Added to the revised plan",
  deltaRemoved: "Removed from the revised plan",
  deltaChanged: "Result changed",
  deltaUnchanged: "No result change",
  revisionFactEditorLegend: "Edit preferred countries",
  revisionFactEditorBody: "Submit only the approved synthetic country scope; the advisor still confirms the fact.",
  revisionCurrentCountries: "Current server fact",
  revisionTargetCountries: "Proposed new scope",
  submitRevisionProposalAction: "Submit change proposal",
  revisionEditorUnavailable: "The current server fact does not match the safe baseline for this synthetic revision.",
  familyRevisionVersionInitial: "Initial planning version",
  familyRevisionVersionRevised: "Current revised plan",
  familyAuthorizationInitial: "Advisor authorized the initial revision",
  familyAuthorizationRenewed: "Advisor renewed authorization for the current revision",
  evidenceOverline: "Evidence disclosure",
  evidenceTitle: "Accepted synthetic evidence and limitations",
  evidencePublisherLabel: "Publisher",
  evidenceLimitationLabel: "Evidence limitation",
  evidenceSnapshotLabel: "Snapshot date",
  taskStatusLabel: "Status",
  taskAttemptLabel: "Attempts",
  taskTrailSummary: "Task trail",
  taskPublicResult: "Public result",
  taskDurablePending: "The durable task record remains available while processing.",
  familyBriefOverline: "Family-safe persisted projection",
  familyBriefTitle: "Family Decision Brief",
  familyBriefOutcome: "The reviewed Brief selects Australia as the eligible route.",
  pinnedCostLabel: "Pinned Australia cost",
  hardCeilingLabel: "Hard ceiling",
  requiredTradeOffLabel: "Required trade-off",
  familyConfirmLabel: "I confirm this server-derived CNY range and accept the Budget flexibility trade-off.",
  familyConfirmAction: "Confirm Australia route",
  familyConfirmationRequired: "Explicit family confirmation is required before continuing.",
  receiptOverline: "Persistent decision trail",
  receiptTitle: "Family Decision Receipt",
  receiptSummary: "The family confirmed the Australia route from the reviewed, persisted Brief.",
  acceptedBudgetLabel: "Accepted budget",
  acceptedTradeOffLabel: "Accepted trade-off",
  decisionSourceLabel: "Decision source",
  timelineTitle: "Action timeline",
  intakeLabel: "intake",
  milestoneDocuments: "Documents",
  milestoneApplication: "Application",
  milestoneVisa: "Visa",
  milestoneArrival: "Arrival",
  recoveryTitle: "Recovery required",
  recoveryInvalidTransition: "The page entered an unsupported state and stopped safely.",
  recoverySessionExpired: "The session expired; reconnect the advisor session.",
  recoverySessionRequired: "A residual session was detected and requires safe recovery.",
  recoveryStaleConflict: "The server record changed; reload it before continuing.",
  recoveryTransportFailure: "The connection is unavailable; no new change was performed.",
  recoveryBoundary: "No mutation or new role authority was assumed.",
  recoveryReconnect: "Reconnect advisor flow",
  journeyConflictTitle: "Another walkthrough is active",
  journeyAdvisorFamily: "advisor-to-family flow",
  journeyCollaboration: "family collaboration flow",
  journeyConflictBody: "The current same-tab flow remains authoritative. End it through the server before starting another flow.",
  journeyReturn: "Return to current flow",
  journeyEnd: "End current flow and continue",
  demoStartOverline: "Local synthetic pilot",
  demoStartTitle: "Advisor-to-family decision flow",
  demoStartBody: "Follow real session, task, advisor review, family decision, receipt, and timeline boundaries.",
  demoStartAction: "Start advisor flow",
  demoSwitchingTitle: "Switching to the family role",
  demoSwitchingBody: "The advisor session was revoked; establishing the parent session.",
  demoSwitchingStudentTitle: "Switching to the student role",
  demoSwitchingStudentBody: "The advisor session was revoked; establishing the student session.",
  demoSwitchingAdvisorTitle: "Switching to the advisor role",
  demoSwitchingAdvisorBody: "The participant session was revoked; restoring advisor authority.",
  continueAsStudentAction: "Continue as student",
  continueAsAdvisorAction: "Continue as advisor",
  continueAsParentAction: "Continue as parent",
  revisionProposalTitle: "Submit the student's preferred-country change",
  revisionProposalBody: "The student submits a visible proposal and does not confirm a Case fact.",
  revisionFactPendingTitle: "Review the student's change proposal",
  revisionFactPendingBody: "Only advisor confirmation lets the server create a new Case revision.",
  loadingStatus: "Loading server authority…",
  busyStatus: "Submitting the change while retaining the last server projection.",
  demoRecordingDecision: "Recording the family decision",
  reasonBudgetAboveHardCeiling: "Above the family hard ceiling",
  reasonBudgetBoundaryExceeded: "Above the family hard ceiling or flexibility boundary",
  claimAustraliaProgramFit: "Australia program fit",
  claimJapanProgramFit: "Japan program fit",
  claimMalaysiaProgramFit: "Malaysia program fit",
  claimAustraliaTuition: "Australia tuition",
  claimAustraliaLivingCost: "Australia living cost",
  claimAustraliaFx: "Australia exchange rate",
  claimAustraliaRanking: "Australia ranking",
  claimJapanTuition: "Japan tuition",
  claimJapanLivingCost: "Japan living cost",
  claimJapanFx: "Japan exchange rate",
  claimJapanRanking: "Japan ranking",
  claimMalaysiaTuition: "Malaysia tuition",
  claimMalaysiaLivingCost: "Malaysia living cost",
  claimMalaysiaFx: "Malaysia exchange rate",
  claimMalaysiaRanking: "Malaysia ranking",
  gapJapanProgramFit: "Missing Japan program-fit evidence",
  gapMalaysiaProgramFit: "Missing Malaysia program-fit evidence",
  gapApplicantEligibility: "Applicant eligibility remains unresolved",
  gapIntakeAvailability: "Intake availability remains unresolved",
  factFamilyBudget: "Total family budget",
  factStudentField: "Intended field",
  factPreferredCountries: "Preferred countries",
  factStudentIntake: "Intended intake",
  factRiskTolerance: "Family risk tolerance",
  factJapanRiskAccepted: "Family accepts Japan route risk",
  factValueRiskLow: "Low",
  factValueRiskMedium: "Medium",
  factValueRiskHigh: "High",
  factValueAccepted: "Accepted",
  factValueNotAccepted: "Not accepted",
  factValueBudgetRefused: "The family chose not to provide a budget",
  publicCancelled: "Task cancelled by the user",
  publicLeaseExpired: "Task lease expired",
  publicEvidenceGap: "Task needs more evidence",
  publicDeadlineExceeded: "Task exceeded its time boundary",
  publicTransportInterrupted: "Task connection interrupted",
  publicTransientUnavailable: "Planning adapter temporarily unavailable",
  threadOverline: "Shared communication record",
  threadTitle: "Shared Case communication record",
  threadLoading: "Loading the server-owned communication record…",
  threadEmpty: "No participant messages yet.",
  messageSequenceLabel: "message",
  messageOriginalLabel: "Original message",
  candidateOverline: "Structured participant proposal",
  candidateTitle: "Budget fact proposal",
  candidateBudgetLabel: "Planning budget",
  candidateSourceLabel: "Source",
  candidateParentMessage: "Parent-authored message",
  candidatePinnedRevision: "Pinned Case revision",
  candidateAdvisorReason: "Advisor reason",
  advisorReasonOriginalLabel: "Original advisor confirmation",
  confirmedFactOverline: "Case authority provenance",
  confirmedFactTitle: "Confirmed family fact",
  confirmedFactProjection: "is now part of the current Case projection.",
  confirmedByLabel: "Confirmed by",
  assignedAdvisor: "Assigned advisor",
  recordedReasonLabel: "Recorded reason",
  collaborationHeroOverline: "Local synthetic pilot · complete collaboration entry",
  collaborationTitle: "Family collaboration and fact confirmation",
  collaborationLede: "A parent message becomes a typed proposal only through an explicit action and becomes a Case fact only after assigned-advisor confirmation.",
  currentRoleLabel: "Current role",
  collaborationPathLabel: "Collaboration authority path",
  pathSharedMessage: "Shared message",
  pathTypedProposal: "Typed proposal",
  pathAdvisorReview: "Advisor review",
  pathConfirmedFact: "Confirmed fact",
  pathCaseRevision: "Case revision",
  pathReplanRequired: "Re-plan required",
  collaborationStartParent: "Start parent flow",
  parentProposeTitle: "Submit one typed family fact",
  parentMessageTitle: "Add the family's confirmed budget",
  parentProposalPending: "The proposal remains pending until the assigned advisor reviews it.",
  parentMessageBoundary: "This message remains communication and does not change the Case.",
  parentProposeAction: "Submit the budget for advisor review",
  parentMessageAction: "Add confirmed budget message",
  recordingMessageTitle: "Recording the parent message",
  recordingMessageAction: "Recording message…",
  moveAdvisorTitle: "Move to advisor review",
  moveAdvisorBody: "The parent session must be revoked before an advisor session is minted.",
  moveAdvisorAction: "Continue as assigned advisor",
  switchingAuthorityTitle: "Switching authority",
  switchingAuthorityBody: "Revoking the parent session and loading the advisor projection.",
  switchingRoleAction: "Switching role…",
  advisorConfirmationTitle: "Advisor confirmation",
  advisorConfirmationBody: "The candidate revision and current Case revision must agree before confirmation.",
  advisorConfirmBudget: "Confirm family budget",
  advisorReloadBoundary: "Reload current Case and candidate authority before confirming.",
  publishingAuthorityTitle: "Publishing confirmed authority",
  publishingAuthorityAction: "Confirming fact and Case revision…",
  replanTitle: "Re-plan required",
  replanBody: "The Case revision changed. This flow creates no task; the destination reloads current authority before the advisor explicitly starts planning.",
  replanAction: "Continue to governed planning",
  handoffTitle: "Validating planning authority",
  handoffBody: "Reloading the current candidate, confirmed fact, Case revision, and advisor ledger before navigation.",
  handoffAction: "Validating authority…",
  collaborationRecoveryTitle: "Collaboration paused safely",
  collaborationRecoveryBoundary: "No message, proposal, role, or Case authority was inferred locally.",
  collaborationRecoveryAction: "Reload collaboration authority",
  skillInspectorTitle: "Planning Skill inspector",
  skillInspectorBody: "This read-only projection comes from the server-owned planning execution record.",
  skillOperationLabel: "Operation",
  skillActiveLabel: "Active Skill",
  skillActivationLabel: "Activation",
  skillSequenceLabel: "Sequence",
  skillEvaluationLabel: "Evaluation",
  skillTaskRequestLabel: "Task request",
  skillVersionContentLabel: "Version content",
  skillRuntimeBindingLabel: "Runtime binding",
  skillAdapterLabel: "Actual adapter",
  skillNoOperation: "Planning task not created",
  skillNoTaskDigest: "No task digest",
  skillNoAdapter: "No recorded leaf adapter",
} satisfies Record<PresentationCopyKey, string>;

const CATALOGS = { "zh-CN": zhCN, en } as const;

export function getPresentationCopy(
  locale: PresentationLocale,
  key: PresentationCopyKey,
): string {
  return CATALOGS[locale][key];
}
