import type { PresentationLocale } from "./locales";

export const zhCN = {
  productName: "Night Voyager",
  productPromise: "你的留学路线应该从你出发",
  statusUnavailable: "状态暂不可用",
  localeChinese: "中文",
  localeEnglish: "English",
  syntheticLabel: "本地合成演示",
  documentTitle: "Night Voyager｜你的留学路线应该从你出发",
  documentDescription: "从学生条件出发，看懂推荐、备选与取舍，再把本地合成路线比较变成可执行计划。",
  contextPortfolio: "作品集入口",
  contextAdvisorFamily: "顾问到家庭决策流程",
  contextCollaboration: "家庭协作与事实确认流程",
  skipToMain: "跳到主要内容",
  localeControlLabel: "展示语言",
  footerBoundary: "本地合成演示，不包含真实学生资料、实时院校覆盖、自动录取建议或生产部署声明。",
  rootKicker: "01 · 从你出发的路线",
  rootEyebrow: "01 · 从你出发的路线",
  rootTitleLineOne: "你的留学路线",
  rootTitleLineTwo: "应该从你出发",
  rootSummary: "不只告诉你去哪留学，更要说清为什么适合你。看懂不同路线的理由与取舍，再把选择变成一份可以执行的计划。",
  rootNavigationLabel: "作品集导航",
  rootNavApproach: "规划思路",
  rootNavRoutes: "路线示例",
  rootNavEvidence: "决策依据",
  rootHeaderAction: "体验完整流程",
  rootOriginLabel: "从学生条件出发",
  rootOriginField: "数据科学",
  rootOriginBudget: "预算 30.55–40 万元",
  rootRouteAtlasTitle: "留学路线比较",
  rootRouteAtlasDescription: "学生希望学习数据科学，预算 30.55–40 万元。澳大利亚为推荐路线，日本为备选路线，马来西亚暂不推荐。",
  rootRouteSummaryLabel: "路线比较摘要",
  rootRouteRecommended: "推荐",
  rootRouteReserve: "备选",
  rootRouteNotRecommended: "暂不推荐",
  rootRouteAustraliaReason: "专业衔接与预算区间更匹配",
  rootRouteJapanReason: "保留语言与时间准备弹性",
  rootRouteMalaysiaReason: "当前专业选择不足以支撑优先级",
  rootJourneyIndex: "02 / 从路线比较到下一步",
  rootJourneyTitleLineOne: "先看清自己",
  rootJourneyTitleLineTwo: "再决定去哪里",
  rootJourneyLead: "同一个专业、同一段预算，会因为你的背景、偏好与承受边界，长出完全不同的路线。Night Voyager 把比较的理由摊开，也把下一步排进日程。",
  rootJourneyStepOneIndex: "01 · 出发点",
  rootJourneyStepOneTitle: "理解你的条件",
  rootJourneyStepOneBody: "专业方向、预算范围和个人偏好，共同构成路线的起点。",
  rootJourneyStepTwoIndex: "02 · 路线比较",
  rootJourneyStepTwoTitle: "看懂理由与取舍",
  rootJourneyStepTwoBody: "推荐、备选与暂不推荐都有清楚依据，差异不藏在结论背后。",
  rootJourneyStepThreeIndex: "03 · 行动坐标",
  rootJourneyStepThreeTitle: "形成可执行计划",
  rootJourneyStepThreeBody: "把选择落到准备顺序和关键节点，让下一步具体而明确。",
  rootScrollCue: "向下读懂这条路线",
  rootOutcomeLabel: "当前目的",
  rootOutcome: "让一次留学选择留下可复核的事实、理由与下一步。",
  rootReasonLabel: "为什么可信",
  rootReason: "消息不是事实；只有经来源、边界和人工确认的内容才进入规划。",
  rootNextLabel: "下一步",
  rootNext: "先体验完整协作流程，或直接查看顾问到家庭的决策链。",
  rootPrimaryAction: "查看示例方案",
  rootSecondaryAction: "查看路线依据",
  rootAuthorityTitle: "同一条 authority chain",
  rootBeatMessageTitle: "家庭表达",
  rootBeatMessageBody: "家庭消息保留在共享沟通记录中，不会静默升级为事实。",
  rootBeatFactTitle: "已确认事实",
  rootBeatFactBody: "顾问确认 typed proposal 后，Case revision 才会变化。",
  rootBeatPlanTitle: "规划与回执",
  rootBeatPlanBody: "证据门、顾问审核和家庭决定共同形成可追溯行动计划。",
  rootScopeTitle: "公开演示边界",
  rootScopeBody: "使用本地合成数据与 deterministic adapters；不调用 live provider，不包含真实学生数据，也不声称生产部署或录取结果。",
  roleAdvisor: "顾问",
  roleStudent: "学生",
  roleParent: "家长",
  countryAustralia: "澳大利亚",
  countryJapan: "日本",
  countryMalaysia: "马来西亚",
  phaseTaskReady: "可以开始规划",
  phaseActiveTask: "正在生成规划",
  phaseReviewRequired: "等待顾问审核",
  phaseFamilyReview: "等待家庭确认",
  phasePlanReady: "行动计划已就绪",
  phaseTerminalTaskFailure: "规划任务已暂停",
  taskPreparing: "正在准备",
  taskNeedsAdvisorReview: "需要顾问审核",
  taskReady: "已完成",
  taskNeedsEvidence: "需要补充证据",
  taskTimedOut: "已超时",
  taskFailed: "未完成",
  taskCancelled: "已取消",
  taskOutdated: "已有更新版本",
  routeRecommendedWithCondition: "在预算条件下推荐",
  routeConditional: "有条件备选",
  routeBlocked: "暂不可选",
  reasonCompleteCostAndFx: "成本与汇率证据均在已批准边界内",
  reasonSyntheticHighRisk: "较高风险的合成备选方案",
  reasonProgramFitAbsent: "缺少直接的项目匹配证据",
  tradeOffBudgetElasticity: "预算弹性",
  candidatePending: "等待顾问确认",
  candidateStale: "所依据的 Case revision 已更新",
  candidateExpired: "候选事实已过期",
  candidateConfirmed: "已确认进入事实记录",
  candidateRejected: "未被采纳",
  errorStale: "页面状态已更新，请重新载入",
  errorExpiredOrTerminal: "该候选事实已结束，不能继续操作",
  errorActiveTaskBlocked: "当前规划任务结束前不能修改事实",
  errorUnsafeOrUnsupported: "输入未通过安全或合同校验",
  errorWrongRoleOrNotFound: "当前角色无法访问该记录",
  errorSessionRecoveryRequired: "会话需要安全恢复",
  errorTransportUnavailable: "连接暂不可用，请稍后重试",
  pinNotCreated: "尚未创建 Skill pin",
  pinMatched: "运行时 Skill pin 已匹配",
  pinLegacyUnpinned: "旧任务没有 Skill pin",
  riskOptional: "可选风险",
  riskStale: "证据可能已过时",
  riskUnverified: "证据尚未验证",
  sourceDirect: "家庭直接确认",
  sourceFamilyConsultation: "家庭协商确认",
  advisorStageTitle: "当前决策阶段",
  advisorStageAuthority: "阶段与可执行动作来自服务器 authority projection。",
  advisorCreateTask: "创建规划任务",
  advisorApproveAustralia: "批准澳大利亚进入家庭审核",
  advisorContinueFamily: "以家庭角色继续",
  advisorTaskInProgress: "任务正在进行",
  advisorActionExplanation: "此阶段只有一个服务器授权的主要动作。",
  routeComparisonLabel: "路线证据比较",
  routeColumn: "路线",
  outcomeColumn: "结果",
  reasonColumn: "理由",
  eligibilityColumn: "审核资格",
  eligibleForReview: "符合审核条件",
  notEligibleForReview: "不符合审核条件",
  compareRoutes: "比较国家路线",
  requiredClaims: "所需证据主张",
  knownGaps: "已知缺口",
  noRequiredClaims: "没有投影的必需主张",
  noKnownGaps: "没有投影的已知缺口",
  noRoutes: "路线比较尚未生成。",
  currentFactsOverline: "服务器持有的当前 Case authority",
  currentFactsTitle: "当前已确认家庭事实",
  currentFactsUnavailable: "服务器事实投影刷新前，当前事实暂不可用。",
  currentFactsEmpty: "此 Case revision 尚无已确认事实。",
  factLabel: "事实",
  currentValueLabel: "当前值",
  factAuthorityLabel: "事实 authority",
  caseAuthorityLabel: "Case authority",
  factVersionLabel: "Fact version",
  caseRevisionLabel: "Case revision",
  evidenceOverline: "证据披露",
  evidenceTitle: "已接受的合成证据与限制",
  evidencePublisherLabel: "发布方",
  evidenceLimitationLabel: "限制",
  evidenceSnapshotLabel: "快照日期",
  taskStatusLabel: "状态",
  taskAttemptLabel: "尝试次数",
  taskTrailSummary: "任务记录",
  taskPublicResult: "公开结果",
  taskDurablePending: "处理期间保留 durable task 记录。",
  familyBriefOverline: "适合家庭阅读的持久化投影",
  familyBriefTitle: "家庭决定简报",
  familyBriefOutcome: "经顾问审核的 Brief 选择澳大利亚作为符合条件的路线。",
  pinnedCostLabel: "澳大利亚锁定成本",
  hardCeilingLabel: "预算硬上限",
  requiredTradeOffLabel: "必须接受的取舍",
  familyConfirmLabel: "我确认这段由服务器生成的人民币区间，并接受预算弹性取舍。",
  familyConfirmAction: "确认澳大利亚路线",
  familyConfirmationRequired: "需要家庭明确确认后才能继续。",
  receiptOverline: "持久化决定记录",
  receiptTitle: "家庭决定回执",
  receiptSummary: "家庭从已审核并持久化的 Brief 中确认了澳大利亚路线。",
  acceptedBudgetLabel: "已接受预算",
  acceptedTradeOffLabel: "已接受取舍",
  decisionSourceLabel: "决定来源",
  timelineTitle: "行动时间线",
  intakeLabel: "入学批次",
  milestoneDocuments: "文件准备",
  milestoneApplication: "提交申请",
  milestoneVisa: "签证准备",
  milestoneArrival: "抵达准备",
  recoveryTitle: "需要恢复",
  recoveryInvalidTransition: "页面进入了不支持的状态，流程已安全停止。",
  recoverySessionExpired: "会话已过期；需要重新建立顾问会话。",
  recoverySessionRequired: "检测到残留会话；需要先执行安全恢复。",
  recoveryStaleConflict: "服务器记录已更新；重新载入后才能继续。",
  recoveryTransportFailure: "连接暂不可用；当前流程没有执行新的变更。",
  recoveryBoundary: "没有执行 mutation，也没有假定新的角色 authority。",
  recoveryReconnect: "重新连接顾问流程",
  journeyConflictTitle: "另一个演示流程正在进行",
  journeyAdvisorFamily: "顾问到家庭流程",
  journeyCollaboration: "家庭协作流程",
  journeyConflictBody: "同一标签页中的当前流程仍具有 authority。开始另一流程前，必须通过服务器结束当前流程。",
  journeyReturn: "返回当前流程",
  journeyEnd: "结束当前流程并继续",
  demoStartOverline: "本地合成试点",
  demoStartTitle: "顾问到家庭的决策流程",
  demoStartBody: "依次经过真实的会话、任务、顾问审核、家庭决定、回执与时间线边界。",
  demoStartAction: "开始顾问流程",
  demoSwitchingTitle: "正在切换到家庭角色",
  demoSwitchingBody: "顾问会话已撤销，正在建立家长会话。",
  demoRecordingDecision: "正在记录家庭决定",
  claimAustraliaProgramFit: "澳大利亚项目匹配",
  claimJapanProgramFit: "日本项目匹配",
  claimMalaysiaProgramFit: "马来西亚项目匹配",
  claimAustraliaTuition: "澳大利亚学费",
  claimAustraliaLivingCost: "澳大利亚生活成本",
  claimAustraliaFx: "澳大利亚汇率",
  claimAustraliaRanking: "澳大利亚排名",
  claimJapanTuition: "日本学费",
  claimJapanLivingCost: "日本生活成本",
  claimJapanFx: "日本汇率",
  claimJapanRanking: "日本排名",
  claimMalaysiaTuition: "马来西亚学费",
  claimMalaysiaLivingCost: "马来西亚生活成本",
  claimMalaysiaFx: "马来西亚汇率",
  claimMalaysiaRanking: "马来西亚排名",
  gapJapanProgramFit: "缺少日本项目匹配证据",
  gapMalaysiaProgramFit: "缺少马来西亚项目匹配证据",
  gapApplicantEligibility: "申请人资格仍待确认",
  gapIntakeAvailability: "入学批次可用性仍待确认",
  factFamilyBudget: "家庭总预算",
  factStudentField: "学生意向专业",
  factPreferredCountries: "意向国家",
  factStudentIntake: "意向入学批次",
  factRiskTolerance: "家庭风险偏好",
  factJapanRiskAccepted: "家庭接受日本路线风险",
  factValueRiskLow: "低",
  factValueRiskMedium: "中等",
  factValueRiskHigh: "高",
  factValueAccepted: "已接受",
  factValueNotAccepted: "未接受",
  factValueBudgetRefused: "家庭选择不提供预算",
  publicCancelled: "任务已由用户取消",
  publicLeaseExpired: "任务租约已过期",
  publicEvidenceGap: "任务需要更多证据",
  publicDeadlineExceeded: "任务超过时间边界",
  publicTransportInterrupted: "任务连接中断",
  publicTransientUnavailable: "规划适配器暂不可用",
  threadOverline: "共享沟通记录",
  threadTitle: "共享 Case 沟通记录",
  threadLoading: "正在加载服务器沟通记录…",
  threadEmpty: "尚无参与者消息。",
  messageSequenceLabel: "消息",
  candidateOverline: "结构化参与者提案",
  candidateTitle: "预算事实提案",
  candidateBudgetLabel: "规划预算",
  candidateSourceLabel: "来源",
  candidateParentMessage: "家长消息",
  candidatePinnedRevision: "锁定的 Case revision",
  candidateAdvisorReason: "顾问理由",
  confirmedFactOverline: "Case authority 来源",
  confirmedFactTitle: "已确认家庭事实",
  confirmedFactProjection: "现已进入当前 Case projection。",
  confirmedByLabel: "确认人",
  assignedAdvisor: "指定顾问",
  recordedReasonLabel: "记录理由",
  collaborationHeroOverline: "本地合成试点 · 完整协作入口",
  collaborationTitle: "家庭协作与事实确认",
  collaborationLede: "家长消息只有经过显式操作才成为 typed proposal，并且只有指定顾问确认后才成为 Case 事实。",
  currentRoleLabel: "当前角色",
  collaborationPathLabel: "协作 authority 路径",
  pathSharedMessage: "共享消息",
  pathTypedProposal: "Typed proposal",
  pathAdvisorReview: "顾问审核",
  pathConfirmedFact: "已确认事实",
  pathCaseRevision: "Case revision",
  pathReplanRequired: "需要重新规划",
  collaborationStartParent: "开始家长流程",
  parentProposeTitle: "提交一项 typed 家庭事实",
  parentMessageTitle: "添加家庭已确认预算",
  parentProposalPending: "提案会保持待处理，直到指定顾问审核。",
  parentMessageBoundary: "这条消息仍是沟通内容，不会改变 Case。",
  parentProposeAction: "提交预算供顾问审核",
  parentMessageAction: "添加已确认预算消息",
  recordingMessageTitle: "正在记录家长消息",
  recordingMessageAction: "正在记录消息…",
  moveAdvisorTitle: "进入顾问审核",
  moveAdvisorBody: "建立顾问会话前，必须先撤销家长会话。",
  moveAdvisorAction: "以指定顾问身份继续",
  switchingAuthorityTitle: "正在切换 authority",
  switchingAuthorityBody: "正在撤销家长会话并载入顾问 projection。",
  switchingRoleAction: "正在切换角色…",
  advisorConfirmationTitle: "顾问确认",
  advisorConfirmationBody: "确认前，候选事实 revision 必须与当前 Case revision 一致。",
  advisorConfirmBudget: "确认家庭预算",
  advisorReloadBoundary: "确认前请重新载入当前 Case 与候选事实 authority。",
  publishingAuthorityTitle: "正在发布已确认 authority",
  publishingAuthorityAction: "正在确认事实与 Case revision…",
  replanTitle: "需要重新规划",
  replanBody: "Case revision 已变化。此流程不会创建任务；目标页面会先重载当前 authority，再由顾问显式启动规划。",
  replanAction: "继续进入受治理规划",
  handoffTitle: "正在验证规划 authority",
  handoffBody: "导航前正在重载当前候选事实、已确认事实、Case revision 与顾问 ledger。",
  handoffAction: "正在验证 authority…",
  collaborationRecoveryTitle: "协作流程已安全暂停",
  collaborationRecoveryBoundary: "本地没有推断消息、提案、角色或 Case authority。",
  collaborationRecoveryAction: "重新载入协作 authority",
  skillInspectorTitle: "规划 Skill 检查器",
  skillInspectorBody: "这个只读 projection 来自服务器持有的规划执行记录。",
  skillOperationLabel: "Operation",
  skillActiveLabel: "Active Skill",
  skillActivationLabel: "Activation",
  skillSequenceLabel: "Sequence",
  skillEvaluationLabel: "Evaluation",
  skillTaskRequestLabel: "Task request",
  skillVersionContentLabel: "Version content",
  skillRuntimeBindingLabel: "Runtime binding",
  skillAdapterLabel: "Actual adapter",
  skillNoOperation: "尚未创建规划任务",
  skillNoTaskDigest: "尚无 task digest",
  skillNoAdapter: "未记录 leaf adapter",
} as const;

export type PresentationCopyKey = keyof typeof zhCN;

export const en = {
  productName: "Night Voyager",
  productPromise: "Your study-abroad route should start with you",
  statusUnavailable: "Status unavailable",
  localeChinese: "中文",
  localeEnglish: "English",
  syntheticLabel: "Local synthetic demo",
  documentTitle: "Night Voyager | A study-abroad route that starts with you",
  documentDescription: "Start with the student, understand each route and trade-off, then turn a local synthetic comparison into an actionable plan.",
  contextPortfolio: "Portfolio entry",
  contextAdvisorFamily: "Advisor-to-family decision flow",
  contextCollaboration: "Family collaboration and fact confirmation",
  skipToMain: "Skip to main content",
  localeControlLabel: "Presentation language",
  footerBoundary: "Local synthetic demo: no real student records, live institutional coverage, automated admissions advice, or production deployment claim.",
  rootKicker: "01 · A route that starts with you",
  rootEyebrow: "01 · A route that starts with you",
  rootTitleLineOne: "Your study-abroad route",
  rootTitleLineTwo: "should start with you",
  rootSummary: "We do more than tell you where to study. We explain why a route fits, make the reasons and trade-offs clear, and turn your choice into an actionable plan.",
  rootNavigationLabel: "Portfolio navigation",
  rootNavApproach: "Approach",
  rootNavRoutes: "Route example",
  rootNavEvidence: "Decision evidence",
  rootHeaderAction: "Experience full flow",
  rootOriginLabel: "Starting from the student",
  rootOriginField: "Data science",
  rootOriginBudget: "Budget CNY 305,500–400,000",
  rootRouteAtlasTitle: "Study-abroad route comparison",
  rootRouteAtlasDescription: "The student plans to study data science with a budget of CNY 305,500–400,000. Australia is recommended, Japan is the reserve route, and Malaysia is not recommended at present.",
  rootRouteSummaryLabel: "Route comparison summary",
  rootRouteRecommended: "Recommended",
  rootRouteReserve: "Reserve",
  rootRouteNotRecommended: "Not recommended at present",
  rootRouteAustraliaReason: "The program pathway and budget range are the strongest match",
  rootRouteJapanReason: "Preserves flexibility for language and timeline preparation",
  rootRouteMalaysiaReason: "Current program options do not support a higher priority",
  rootJourneyIndex: "02 / From route comparison to the next step",
  rootJourneyTitleLineOne: "Understand yourself first",
  rootJourneyTitleLineTwo: "then decide where to go",
  rootJourneyLead: "The same field and budget can lead to very different routes once your background, preferences, and limits are considered. Night Voyager makes the reasons visible and puts the next step on a timeline.",
  rootJourneyStepOneIndex: "01 · Starting point",
  rootJourneyStepOneTitle: "Understand your conditions",
  rootJourneyStepOneBody: "Your intended field, budget range, and personal preferences define the route's starting point.",
  rootJourneyStepTwoIndex: "02 · Route comparison",
  rootJourneyStepTwoTitle: "See the reasons and trade-offs",
  rootJourneyStepTwoBody: "Recommended, reserve, and not-recommended routes all have clear reasons, with differences visible behind each conclusion.",
  rootJourneyStepThreeIndex: "03 · Action coordinates",
  rootJourneyStepThreeTitle: "Form an actionable plan",
  rootJourneyStepThreeBody: "Turn the choice into a preparation order and key milestones so the next step is concrete.",
  rootScrollCue: "Scroll to understand this route",
  rootOutcomeLabel: "Purpose",
  rootOutcome: "Leave every study-abroad choice with reviewable facts, reasons, and a next action.",
  rootReasonLabel: "Why it is trustworthy",
  rootReason: "A message is not a fact; only sourced, bounded, and human-confirmed material enters planning.",
  rootNextLabel: "Next action",
  rootNext: "Experience the complete collaboration flow or go directly to the advisor-to-family decision chain.",
  rootPrimaryAction: "View the example plan",
  rootSecondaryAction: "View route evidence",
  rootAuthorityTitle: "One authority chain",
  rootBeatMessageTitle: "Family expression",
  rootBeatMessageBody: "Family messages remain in the shared communication record and never silently become facts.",
  rootBeatFactTitle: "Confirmed fact",
  rootBeatFactBody: "The Case revision changes only after an advisor confirms a typed proposal.",
  rootBeatPlanTitle: "Plan and receipt",
  rootBeatPlanBody: "Evidence gates, advisor review, and a family decision produce a traceable action plan.",
  rootScopeTitle: "Public demo boundary",
  rootScopeBody: "Uses local synthetic data and deterministic adapters; no live provider, real student data, production deployment claim, or admissions outcome.",
  roleAdvisor: "Advisor",
  roleStudent: "Student",
  roleParent: "Parent",
  countryAustralia: "Australia",
  countryJapan: "Japan",
  countryMalaysia: "Malaysia",
  phaseTaskReady: "Ready to plan",
  phaseActiveTask: "Planning in progress",
  phaseReviewRequired: "Advisor review required",
  phaseFamilyReview: "Family confirmation required",
  phasePlanReady: "Action plan ready",
  phaseTerminalTaskFailure: "Planning task paused",
  taskPreparing: "Preparing",
  taskNeedsAdvisorReview: "Needs advisor review",
  taskReady: "Ready",
  taskNeedsEvidence: "Needs more evidence",
  taskTimedOut: "Timed out",
  taskFailed: "Failed",
  taskCancelled: "Cancelled",
  taskOutdated: "Superseded",
  routeRecommendedWithCondition: "Recommended with budget condition",
  routeConditional: "Conditional alternative",
  routeBlocked: "Blocked",
  reasonCompleteCostAndFx: "Cost and FX evidence are within the approved boundary",
  reasonSyntheticHighRisk: "Higher-risk synthetic alternative",
  reasonProgramFitAbsent: "Program-fit evidence is missing",
  tradeOffBudgetElasticity: "Budget flexibility",
  candidatePending: "Awaiting advisor confirmation",
  candidateStale: "Based on an older Case revision",
  candidateExpired: "Candidate fact expired",
  candidateConfirmed: "Confirmed in the fact record",
  candidateRejected: "Not accepted",
  errorStale: "The page state changed; reload before continuing",
  errorExpiredOrTerminal: "This candidate fact has ended and cannot continue",
  errorActiveTaskBlocked: "Facts cannot change while a planning task is active",
  errorUnsafeOrUnsupported: "The input did not pass safety or contract validation",
  errorWrongRoleOrNotFound: "This role cannot access the record",
  errorSessionRecoveryRequired: "The session needs a safe recovery",
  errorTransportUnavailable: "The connection is unavailable; try again",
  pinNotCreated: "Skill pin not created",
  pinMatched: "Runtime Skill pin matched",
  pinLegacyUnpinned: "Legacy task has no Skill pin",
  riskOptional: "Optional risk",
  riskStale: "Evidence may be stale",
  riskUnverified: "Evidence is unverified",
  sourceDirect: "Direct family confirmation",
  sourceFamilyConsultation: "Family consultation",
  advisorStageTitle: "Current decision stage",
  advisorStageAuthority: "The stage and available action come from the server authority projection.",
  advisorCreateTask: "Create planning task",
  advisorApproveAustralia: "Approve Australia for family review",
  advisorContinueFamily: "Continue as family",
  advisorTaskInProgress: "Task in progress",
  advisorActionExplanation: "One server-authorized primary action is available in this stage.",
  routeComparisonLabel: "Route evidence comparison",
  routeColumn: "Route",
  outcomeColumn: "Outcome",
  reasonColumn: "Reason",
  eligibilityColumn: "Eligibility",
  eligibleForReview: "Eligible for review",
  notEligibleForReview: "Not eligible for review",
  compareRoutes: "Compare country routes",
  requiredClaims: "Required claims",
  knownGaps: "Known gaps",
  noRequiredClaims: "No projected required claims",
  noKnownGaps: "No projected known gaps",
  noRoutes: "Route comparison has not been generated.",
  currentFactsOverline: "Current server-owned Case authority",
  currentFactsTitle: "Current confirmed family facts",
  currentFactsUnavailable: "Current facts are unavailable until the server projection refreshes.",
  currentFactsEmpty: "No confirmed facts are projected for this Case revision.",
  factLabel: "Fact",
  currentValueLabel: "Current value",
  factAuthorityLabel: "Fact authority",
  caseAuthorityLabel: "Case authority",
  factVersionLabel: "Fact version",
  caseRevisionLabel: "Case revision",
  evidenceOverline: "Evidence disclosure",
  evidenceTitle: "Accepted synthetic evidence and limitations",
  evidencePublisherLabel: "Publisher",
  evidenceLimitationLabel: "Limitation",
  evidenceSnapshotLabel: "Snapshot date",
  taskStatusLabel: "Status",
  taskAttemptLabel: "Attempts",
  taskTrailSummary: "Task trail",
  taskPublicResult: "Public result",
  taskDurablePending: "The durable task record remains available while processing.",
  familyBriefOverline: "Family-safe persisted projection",
  familyBriefTitle: "Family Decision Brief",
  familyBriefOutcome: "The reviewed Brief selects Australia as the eligible route.",
  pinnedCostLabel: "Pinned Australia cost",
  hardCeilingLabel: "Hard ceiling",
  requiredTradeOffLabel: "Required trade-off",
  familyConfirmLabel: "I confirm this server-derived CNY range and accept the Budget flexibility trade-off.",
  familyConfirmAction: "Confirm Australia route",
  familyConfirmationRequired: "Explicit family confirmation is required before continuing.",
  receiptOverline: "Persistent decision trail",
  receiptTitle: "Family Decision Receipt",
  receiptSummary: "The family confirmed the Australia route from the reviewed, persisted Brief.",
  acceptedBudgetLabel: "Accepted budget",
  acceptedTradeOffLabel: "Accepted trade-off",
  decisionSourceLabel: "Decision source",
  timelineTitle: "Action timeline",
  intakeLabel: "intake",
  milestoneDocuments: "Documents",
  milestoneApplication: "Application",
  milestoneVisa: "Visa",
  milestoneArrival: "Arrival",
  recoveryTitle: "Recovery required",
  recoveryInvalidTransition: "The page entered an unsupported state and stopped safely.",
  recoverySessionExpired: "The session expired; reconnect the advisor session.",
  recoverySessionRequired: "A residual session was detected and requires safe recovery.",
  recoveryStaleConflict: "The server record changed; reload it before continuing.",
  recoveryTransportFailure: "The connection is unavailable; no new change was performed.",
  recoveryBoundary: "No mutation or new role authority was assumed.",
  recoveryReconnect: "Reconnect advisor flow",
  journeyConflictTitle: "Another walkthrough is active",
  journeyAdvisorFamily: "advisor-to-family flow",
  journeyCollaboration: "family collaboration flow",
  journeyConflictBody: "The current same-tab flow remains authoritative. End it through the server before starting another flow.",
  journeyReturn: "Return to current flow",
  journeyEnd: "End current flow and continue",
  demoStartOverline: "Local synthetic pilot",
  demoStartTitle: "Advisor-to-family decision flow",
  demoStartBody: "Follow real session, task, advisor review, family decision, receipt, and timeline boundaries.",
  demoStartAction: "Start advisor flow",
  demoSwitchingTitle: "Switching to the family role",
  demoSwitchingBody: "The advisor session was revoked; establishing the parent session.",
  demoRecordingDecision: "Recording the family decision",
  claimAustraliaProgramFit: "Australia program fit",
  claimJapanProgramFit: "Japan program fit",
  claimMalaysiaProgramFit: "Malaysia program fit",
  claimAustraliaTuition: "Australia tuition",
  claimAustraliaLivingCost: "Australia living cost",
  claimAustraliaFx: "Australia exchange rate",
  claimAustraliaRanking: "Australia ranking",
  claimJapanTuition: "Japan tuition",
  claimJapanLivingCost: "Japan living cost",
  claimJapanFx: "Japan exchange rate",
  claimJapanRanking: "Japan ranking",
  claimMalaysiaTuition: "Malaysia tuition",
  claimMalaysiaLivingCost: "Malaysia living cost",
  claimMalaysiaFx: "Malaysia exchange rate",
  claimMalaysiaRanking: "Malaysia ranking",
  gapJapanProgramFit: "Missing Japan program-fit evidence",
  gapMalaysiaProgramFit: "Missing Malaysia program-fit evidence",
  gapApplicantEligibility: "Applicant eligibility remains unresolved",
  gapIntakeAvailability: "Intake availability remains unresolved",
  factFamilyBudget: "Total family budget",
  factStudentField: "Intended field",
  factPreferredCountries: "Preferred countries",
  factStudentIntake: "Intended intake",
  factRiskTolerance: "Family risk tolerance",
  factJapanRiskAccepted: "Family accepts Japan route risk",
  factValueRiskLow: "Low",
  factValueRiskMedium: "Medium",
  factValueRiskHigh: "High",
  factValueAccepted: "Accepted",
  factValueNotAccepted: "Not accepted",
  factValueBudgetRefused: "The family chose not to provide a budget",
  publicCancelled: "Task cancelled by the user",
  publicLeaseExpired: "Task lease expired",
  publicEvidenceGap: "Task needs more evidence",
  publicDeadlineExceeded: "Task exceeded its time boundary",
  publicTransportInterrupted: "Task connection interrupted",
  publicTransientUnavailable: "Planning adapter temporarily unavailable",
  threadOverline: "Shared communication record",
  threadTitle: "Shared Case communication record",
  threadLoading: "Loading the server-owned communication record…",
  threadEmpty: "No participant messages yet.",
  messageSequenceLabel: "message",
  candidateOverline: "Structured participant proposal",
  candidateTitle: "Budget fact proposal",
  candidateBudgetLabel: "Planning budget",
  candidateSourceLabel: "Source",
  candidateParentMessage: "Parent-authored message",
  candidatePinnedRevision: "Pinned Case revision",
  candidateAdvisorReason: "Advisor reason",
  confirmedFactOverline: "Case authority provenance",
  confirmedFactTitle: "Confirmed family fact",
  confirmedFactProjection: "is now part of the current Case projection.",
  confirmedByLabel: "Confirmed by",
  assignedAdvisor: "Assigned advisor",
  recordedReasonLabel: "Recorded reason",
  collaborationHeroOverline: "Local synthetic pilot · complete collaboration entry",
  collaborationTitle: "Family collaboration and fact confirmation",
  collaborationLede: "A parent message becomes a typed proposal only through an explicit action and becomes a Case fact only after assigned-advisor confirmation.",
  currentRoleLabel: "Current role",
  collaborationPathLabel: "Collaboration authority path",
  pathSharedMessage: "Shared message",
  pathTypedProposal: "Typed proposal",
  pathAdvisorReview: "Advisor review",
  pathConfirmedFact: "Confirmed fact",
  pathCaseRevision: "Case revision",
  pathReplanRequired: "Re-plan required",
  collaborationStartParent: "Start parent flow",
  parentProposeTitle: "Submit one typed family fact",
  parentMessageTitle: "Add the family's confirmed budget",
  parentProposalPending: "The proposal remains pending until the assigned advisor reviews it.",
  parentMessageBoundary: "This message remains communication and does not change the Case.",
  parentProposeAction: "Submit the budget for advisor review",
  parentMessageAction: "Add confirmed budget message",
  recordingMessageTitle: "Recording the parent message",
  recordingMessageAction: "Recording message…",
  moveAdvisorTitle: "Move to advisor review",
  moveAdvisorBody: "The parent session must be revoked before an advisor session is minted.",
  moveAdvisorAction: "Continue as assigned advisor",
  switchingAuthorityTitle: "Switching authority",
  switchingAuthorityBody: "Revoking the parent session and loading the advisor projection.",
  switchingRoleAction: "Switching role…",
  advisorConfirmationTitle: "Advisor confirmation",
  advisorConfirmationBody: "The candidate revision and current Case revision must agree before confirmation.",
  advisorConfirmBudget: "Confirm family budget",
  advisorReloadBoundary: "Reload current Case and candidate authority before confirming.",
  publishingAuthorityTitle: "Publishing confirmed authority",
  publishingAuthorityAction: "Confirming fact and Case revision…",
  replanTitle: "Re-plan required",
  replanBody: "The Case revision changed. This flow creates no task; the destination reloads current authority before the advisor explicitly starts planning.",
  replanAction: "Continue to governed planning",
  handoffTitle: "Validating planning authority",
  handoffBody: "Reloading the current candidate, confirmed fact, Case revision, and advisor ledger before navigation.",
  handoffAction: "Validating authority…",
  collaborationRecoveryTitle: "Collaboration paused safely",
  collaborationRecoveryBoundary: "No message, proposal, role, or Case authority was inferred locally.",
  collaborationRecoveryAction: "Reload collaboration authority",
  skillInspectorTitle: "Planning Skill inspector",
  skillInspectorBody: "This read-only projection comes from the server-owned planning execution record.",
  skillOperationLabel: "Operation",
  skillActiveLabel: "Active Skill",
  skillActivationLabel: "Activation",
  skillSequenceLabel: "Sequence",
  skillEvaluationLabel: "Evaluation",
  skillTaskRequestLabel: "Task request",
  skillVersionContentLabel: "Version content",
  skillRuntimeBindingLabel: "Runtime binding",
  skillAdapterLabel: "Actual adapter",
  skillNoOperation: "Planning task not created",
  skillNoTaskDigest: "No task digest",
  skillNoAdapter: "No recorded leaf adapter",
} satisfies Record<PresentationCopyKey, string>;

const CATALOGS = { "zh-CN": zhCN, en } as const;

export function getPresentationCopy(
  locale: PresentationLocale,
  key: PresentationCopyKey,
): string {
  return CATALOGS[locale][key];
}
